version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-php-fpm
        ports:
            - "8080:80"

    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./manager:/app
        depends_on:
          - manager-postgres
          - manager-redis
          - mailer

    manager-php-cli:
        build:
            context: ./manager/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./manager:/app
            - composer:/root/.composer/cache
        depends_on:
          - manager-postgres
          - manager-redis
          - mailer

    manager-node:
        image: library/node:14.2-alpine
        volumes:
            - ./manager:/app
        working_dir: /app

    manager-node-watch:
        image: library/node:14.2-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"

    manager-postgres:
        image: postgres:12.2-alpine
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"

    manager-redis:
        image: redis:5.0-alpine
        volumes:
            - manager-redis:/data
        command:
            - 'redis-server'
            - '--databases 2'
            - '--save 900 1'
            - '--save 300 10'
            - '--save 60 10000'
            - '--requirepass secret'

    mailer:
        image: mailhog/mailhog
        ports:
            - "8081:8025"

volumes:
    manager-postgres:
    manager-redis:
    composer: